# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AqYSg_6QnHhMeAYbfbohMDFyY92fx3fN
"""

[https://www.kaggle.com/mirbektoktogaraev/should-this-loan-be-approved-or-denied|LINK]
https://www.pewresearch.org/fact-tank/2014/12/12/racial-wealth-gaps-great-recession/ 
https://s3.amazonaws.com/files.consumerfinance.gov/f/documents/bcfp_hmda_2017-mortgage-market- activity-trends_report.pdf

"""Action Item:
Think about a real-world problem and see if you can find a dataset that has the characteristics of the data of that problem. Then, think about the deep learning algorithm that you would likely use to develop a solution to it. Outline why you picked a particular approach.

Share the dataset you found and your reasons in the Responses section of your README.
Share links with your mentor on your Localized team channel. 


I would have love to see dicrioencies between home owners and gender, or names, or citizenship, or amount of childern or marital stautus had an effect on home loan approval. Since home owner information isn't publically avaliable, I looked at home owner approval on the basis of race. With machine learning(or AI algorithms) now being able to decide whether or not to approve a home loan, they have less responsibility when it comes to their decision making. Thus, allowing companies to not approve a canidate without any reasoning.

Now looking at the various data sets and analysziations, we can see on average people who tend to make more have lower intreast(loan) rates on their loans and are more likely to get home loans. With Asain Families having the most home loans(pews research) while Black Families have the least amount of loans and highest intreast rates. It could be the result of perceived sterotypes about both groups thus causing loans to be handeled differntly so I have a suggestion. Loan applications shouldn't ask for the race of the loaner. Now this may not solve anything becuase names can be pretty identifiable as well so not including gender, so not including gender and name will also help the loaner make decisions based on other factors.
"""